# Generated by Django 4.1.7 on 2023-03-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_autor_fecha_creacion_libro_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
