# Generated by Django 4.1.7 on 2023-03-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_autor_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
    ]
